### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: ./backward_warp_op.so: undefined symbol: __cudaPushCallConfiguration

### ISSUE THREAD

**Issue by MrYANG23** [simonmeister/UnFlow#56]
Hi thanks your work ,
when i run run.py --help i got this error :tensorflow.python.framework.errors_impl.NotFoundError: ./backward_warp_op.so: undefined symbol: __cudaPushCallConfiguration
Traceback (most recent call last):
  File "/home/yh/下载/UnFlow-master/src/e2eflow/ops.py", line 59, in <module>
    op_lib = tf.load_op_library(lib_path)
  File "/home/yh/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: ./backward_warp_op.so: cannot open shared object file: No such file or directory
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/yh/下载/UnFlow-master/src/run.py", line 7, in <module>
    from e2eflow.core.train import Trainer
  File "/home/yh/下载/UnFlow-master/src/e2eflow/core/train.py", line 11, in <module>
    from . import util
  File "/home/yh/下载/UnFlow-master/src/e2eflow/core/util.py", line 2, in <module>
    from ..ops import downsample as downsample_ops
  File "/home/yh/下载/UnFlow-master/src/e2eflow/ops.py", line 62, in <module>
    op_lib = tf.load_op_library(lib_path)
  File "/home/yh/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: ./backward_warp_op.so: undefined symbol: __cudaPushCallConfiguration

can you give me some advices ,thank you sou much!

**Comment by simonmeister** [comment]
Did you compile the custom ops? It seems it can't find them.

**Comment by GallonDeng** [comment]
I run eval_gui.py, also got errors:
1 error detected in the compilation of tmp/tmpxft_00004b70_00000000-6_backward_warp_op.cu.cpp1.ii"
tensorflow.python.framework.errors_impl.NotFoundError: ./backward_warp_op.so: cannot open shared object file: No such file or directory
subprocess.CalledProcessError: Command 'nvcc -std=c++11 -c -o backward_warp_op.cu.o backward_warp_op.cu.cc -I/home/dfc/anaconda3/lib/python3.6/site-packages/tensorflow/include -D_GLIBCXX_USE_CXX11_ABI=0 -L/home/dfc/anaconda3/lib/python3.6/site-packages/tensorflow -ltensorflow_framework -D GOOGLE_CUDA=1 -x cu -Xcompiler -fPIC -I /usr/local --expt-relaxed-constexpr' returned non-zero exit status 1.

My OS is gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609 and tensorflow1.12. Is it related to gcc version or not? Thanks

**Comment by Fanpanda** [comment]
Hi, do you solve this problem? @AllenDun @MrYANG23

**Comment by MrYANG23** [comment]
> Hi, do you solve this problem? @AllenDun @MrYANG23 
i didnt solve this problem,i am trying reimplement this repo with pytorch again

**Comment by Fanpanda** [comment]
Thanks for your reply.

**Comment by 3bhady** [comment]
@AllenDun I have the same issue. Have you had any luck with solving it?
@MrYANG23 did you implement it with pytorch?

**Comment by simonmeister** [comment]
Which version of cuda and cudnn are you using? After a quick search, it may be a problem with newer versions similar to https://github.com/pytorch/pytorch/issues/15433.

**Comment by 3bhady** [comment]
I'm running it on colab 
`Cuda compilation tools, release 10.0, V10.0.130`

**Comment by aadilmehdis** [comment]
Was anyone able to fix this?

**Comment by simonmeister** [comment]
Did you try it with version 1.2 or 1.7 of tensorflow? I wasn't able to test a more recent version due to high workload from new projects.

**Comment by PEIWANG28** [comment]
> > Hi, do you solve this problem? @AllenDun @MrYANG23
> > i didnt solve this problem,i am trying reimplement this repo with pytorch again

hi，Is this implemented with pytorch?
