### ISSUE TITLE
error: constexpr function return is non-constant

### ISSUE THREAD

**Issue by ooFormalinoo** [simonmeister/UnFlow#61]
I use tf1.13,cuda10.0 and g++-4.8,and my os is ubuntu16.04.However,when I run python run.py --help,some errors occur：

/usr/local/lib/python3.5/dist-packages/tensorflow/include/absl/strings/string_view.h(496): 
error: constexpr function return is non-constant

/usr/local/lib/python3.5/dist-packages/tensorflow/include/google/protobuf/arena_impl.h(55):
 warning: integer conversion resulted in a change of sign

/usr/local/lib/python3.5/dist-packages/tensorflow/include/google/protobuf/arena_impl.h(309):
 warning: integer conversion resulted in a change of sign

/usr/local/lib/python3.5/dist-packages/tensorflow/include/google/protobuf/arena_impl.h(310):
 warning: integer conversion resulted in a change of sign

1 error detected in the compilation of "/tmp/tmpxft_00003790_00000000-6_backward_warp_op.cu.cpp1.ii".

Traceback (most recent call last):
  File "/home/kjq/UnFlow/src/e2eflow/ops.py", line 59, in <module>
    op_lib = tf.load_op_library(lib_path)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: ./backward_warp_op.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "run.py", line 7, in <module>
    from e2eflow.core.train import Trainer
  File "/home/kjq/UnFlow/src/e2eflow/core/train.py", line 11, in <module>
    from . import util
  File "/home/kjq/UnFlow/src/e2eflow/core/util.py", line 2, in <module>
    from ..ops import downsample as downsample_ops
  File "/home/kjq/UnFlow/src/e2eflow/ops.py", line 61, in <module>
    compile(n)
  File "/home/kjq/UnFlow/src/e2eflow/ops.py", line 43, in compile
    subprocess.check_output(nvcc_cmd, shell=True)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'nvcc -std=c++11 -c -o backward_warp_op.cu.o backward_warp_op.cu.cc -I/usr/local/lib/python3.5/dist-packages/tensorflow/include -D_GLIBCXX_USE_CXX11_ABI=0 -L/usr/local/lib/python3.5/dist-packages/tensorflow -ltensorflow_framework -D GOOGLE_CUDA=1 -x cu -Xcompiler -fPIC -I /usr/local --expt-relaxed-constexpr' returned non-zero exit status 1

could you give some advices ？

**Comment by chulie9710** [comment]
hello, I have the same issue,
Did you solve the problem?
